# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            The Three Laws Blog
tagline:          'Educating lawmakers about AI and discussing regulation.'
description:      'News and Discussion on Artificial Intelligence Law.'
url:              http://nerdyfergy.github.io/hyde/
baseurl:          /

author:
  name:           'Alex Ferguson'
  url:            https://bamboolawgroup.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
