# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Three Laws Blog
tagline:          'A legal blog about Artificial Intelligence regulations, policies, and laws.'
description:      'Educating lawmakers about AI and discussing regulation.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Alex Ferguson'
  url:            https://bamboolawgroup.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
