# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Three Laws Blog
tagline:          'A legal blog about Artificial Intelligence regulations, policies, and laws.'
description:      'The purpose of this blog is to
	1. Educate attorneys and law makers about the emerging field of Artificial Intelligence, and 
	2. Create a discussion within the legal field about what can/should be done in regards to regulating Artificial Intelligence research and development
'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Alex Ferguson'
  url:            https://bamboolawgroup.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
